services:
  postgres:
    image: postgres:16
    container_name: stock_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpass
      POSTGRES_DB: stockdb
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pipeline_net

volumes:
  pg_data:

networks:
  pipeline_net:
    name: pipeline_net